---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: php-apache
 labels:
   app: php
spec:
  selector:
   matchLabels:
     app: php
  template:
    metadata:
      name: php-apache
      labels:
       app: php
    spec:
     containers:
     - name: php-apache
       image: intelliqit/mynew
       resources:
        requests:
          cpu: 200m
        limits:
          cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: php-apache
  labels:
    app: php
spec:
 type: ClusterIP
 ports:
   - targetPort: 80
     port: 80
 selector:
   app: php
...






