---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  namespace: test-ns
  labels:
    app: website
    author: intelliiit
spec:
  replicas: 2
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      name: wordpress-pod
      labels:
        app: website
    spec:
      containers:
        - name: mywordpress
          image: wordpress
          ports:
            - containerPort: 80
              hostPort: 8080
...




