apiVersion: v1
kind: PersistentVolume
metadata:
  name: new-pv
  labels:
   type: local
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20G
  hostPath: 
    path: /tmp
...
