apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
  labels:
   type: local
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10G
  hostPath: 
    path: /mnt/data
...
