---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: wordpress-rs
  namespace: test-ns
  labels:
    app: cms
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cms
  template:
    metadata:
      name: wordpress-pod
      labels:
        app: cms
    spec:
      containers:
        - name: mywordpress
          image: wordpress
          ports:
            - containerPort: 80
              hostPort: 9090



