apiVersion: v1
kind: Pod 
metadata:
  name: mysql-pod
  labels:
   type: db
spec:
  containers:
   - name: mydb
     image: mysql
     env:
      - name: MYSQL_ROOT_PASSWORD
        value: intelliqit
     volumeMounts:
       - name: mysqlvolume
         mountPath: /var/lib/mysql
  volumes:
   - name: mysqlvolume
     persistentVolumeClaim:
      claimName: new-pvc
...


